package lib;

import java.io.*;
import java.sql.*;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;

public class Main extends javax.swing.JFrame {
    //定义背景图片变量  
    private final JPanel imagePanel; //JPanel类型的图片面板
    private final ImageIcon background; //图片图表类型的背景

    public Main() {
        setBounds(250, 150, 900, 562);//设置JFrame 尺寸、位置
        setTitle("图书管理系统");//标题
        setResizable(false);//使用者不可更改窗口的大小
        initComponents();//初始化面板   
        BufferedImage image = null;//初始化背景图片
        try {
            image = ImageIO.read(new File("src\\image\\bg.jpg"));//图片接口位置
        } catch (IOException e) {
            e.printStackTrace();//捕获异常
        }
        background = new ImageIcon(image);
        JLabel label = new JLabel(background);//把背景图片显示到标签里面
        label.setBounds(0, 0, background.getIconWidth(), background.getIconHeight());//背景图片的尺寸为JFrame界面大小
        imagePanel = (JPanel) getContentPane();//初始化容器
        imagePanel.setOpaque(false);//面板透明化
        getLayeredPane().add(label, new Integer(Integer.MIN_VALUE));//把背景图片添加到分层窗格的最底层作为背景
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//关闭窗口
        setSize(background.getIconWidth(), background.getIconHeight());
        setVisible(true);//设置可视
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("用户名：");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 170, 25));

        jLabel5.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("密  码：");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jButton1.setText("读者登陆");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 100, 25));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jButton2.setText("管理员登陆");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 120, 25));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 170, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = null; //调用类AcessDB和其方法connection
        AcessDB adb = new AcessDB();
        con = adb.ADB();
        Statement st;
        try {
            //登陆，相当于SQL的查询功能，读者输入的账号密码与数据库中数据匹配即可登陆成功 
            st = con.createStatement();
            String sql = "SELECT * FROM READER WHERE rno='" + jTextField1.getText() + "'and password='" + jPasswordField1.getText() + "'";
            ResultSet rs = st.executeQuery(sql);//查询
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "登陆成功");//登陆成功对话框
                rs.close();//关闭查询           
                st.close();//关闭驱动
                setVisible(false);//关闭登陆界面
                Reader reader = new Reader();//调用类Reader
                reader.getName(jTextField1.getText());//读取用户输入的信息
                reader.setVisible(true);//跳转读者界面              
            } else {
                JOptionPane.showMessageDialog(this, "用户名或密码错误");//账号或密码输错会触发此消息框
            }
        } catch (SQLException ex) {
        } finally {
            try {
                con.close();//关闭数据库连接
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        Connection con = null; //调用类AcessDB和其方法connection
        AcessDB adb = new AcessDB();
        con = adb.ADB();
        Statement st;
        try {       //登陆，相当于SQL的查询功能，管理员输入的账号密码与数据库中数据匹配即可登陆成功 
            st = con.createStatement();
            String sql = "SELECT * FROM MANAGER WHERE admin='" + jTextField1.getText() + "'and password='" + jPasswordField1.getText() + "'";
            ResultSet rs = st.executeQuery(sql);//查询
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "登陆成功");//登陆成功对话框
                rs.close();//关闭查询  
                st.close();//关闭驱动
                setVisible(false);//关闭登陆界面
                Manager manager = new Manager();//调用类Manager
                manager.setVisible(true);//跳转管理员界面 
            } else {
                JOptionPane.showMessageDialog(this, "用户名或密码错误");//账号或密码输错会触发此消息框
            }
        } catch (SQLException ex) {
        } finally {
            try {
                con.close();//关闭数据库连接
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);//设置主界面可视
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
