/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib;

import java.io.*;
import java.sql.*;
import javax.swing.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Reader extends javax.swing.JFrame {
     private final JPanel imagePanel ;//JPanel类型的图片面板
     private final ImageIcon background;//图片图表类型的背景
    /**
     * Creates new form Reader
     */
     String name="";
    public void getName(String s){
        name=s;
    }
    public Reader() {
        setBounds(250,150,900,562); //设定窗体位置
        setTitle("读者自助系统"); //设置标题
        setResizable(false);//使用者不可更改窗口的大小
        initComponents();//初始化窗体框架
        
        Hyalinize h=new Hyalinize(jTable1,jScrollPane1);//使表格透明化
        Hyalinize q=new Hyalinize(jTable3,jScrollPane3);//使表格透明化
        Hyalinize w=new Hyalinize(jTable4,jScrollPane4);//使表格透明化
        
        BufferedImage image=null; //初始化背景图片
        try {
    image=ImageIO.read(new File("src\\image\\bg1.jpg"));//图片接口位置
    } catch (IOException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
    }
            background = new ImageIcon(image);
            JLabel label = new JLabel(background);//把背景图片显示到标签里面
            label.setBounds(0,0,background.getIconWidth(),background.getIconHeight()); //背景图片的尺寸为JFrame界面大小
            imagePanel = (JPanel)getContentPane();//初始化容器
            imagePanel.setOpaque(false);//面板透明化
            getLayeredPane().add(label,new Integer(Integer.MIN_VALUE));//把背景图片添加到分层窗格的最底层作为背景    
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//关闭窗口
            setSize(background.getIconWidth(),background.getIconHeight());            
            setVisible(true);//设置可视           
            jTable1.setShowHorizontalLines(false); 
            jTable1.setShowVerticalLines(false); 
            jTable3.setShowHorizontalLines(false); 
            jTable3.setShowVerticalLines(false); 
            jTable4.setShowHorizontalLines(false); 
            jTable4.setShowVerticalLines(false); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "图书号", "图书名", "作者", "出版社", "ISBN", "剩余书量", "图书位置"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 890, 190));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("欢迎你，读者！");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        jTextField1.setText("请输入关键字...");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 800, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("模糊查找");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("借书情况");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("查询");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("还书情况");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "已借书号", "已借书名", "借书日期"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 428, 109));

        jTable4.setForeground(new java.awt.Color(255, 255, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "已借书号", "已借书名", "还书日期"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 428, 109));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("查询");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("确定修改");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, 40));

        jLabel4.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("修改密码：");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, 50));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 150, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 190, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Connection con = null;//调用类AcessDB和其方法connection
        AcessDB adb=new AcessDB();//建立sql数据库连接
        con=adb.ADB();
        Statement st;
        try {
            st = con.createStatement();//建立数据库连接
            String sql = "SELECT * FROM BOOK WHERE bname LIKE '%" + jTextField1.getText() + "%' OR author LIKE '%" + jTextField1.getText() + "%' OR bpc LIKE '%" + jTextField1.getText() + "%'";//查找数据库符合文本框内容的行  
            a=jTextField1.getText();//将搜索框内容传输给全局变量a，再传输到各个方法
            ResultSet rs = st.executeQuery(sql);//查询
            DefaultTableModel TableModel = (DefaultTableModel) jTable1.getModel();//初始化表格
            TableModel.setRowCount(0);//清空表格内容
            while (rs.next()) {//将搜索结果导入表格
                TableModel.addRow(new Object[]{rs.getString("bno"), rs.getString("bname"), rs.getString("author"), rs.getString("bpc"), rs.getString("ISBN"), rs.getString("bnum"), rs.getString("bshelf")});
            }
            rs.close();//关闭查询 
            st.close();//关闭驱动

        } catch (SQLException ex) {
        } finally {
            try {
                con.close();//关闭数据库连接
            } catch (SQLException ex) {

            }
        }
          
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Connection con = null;//调用类AcessDB和其方法connection
        AcessDB adb=new AcessDB();//建立sql数据库连接
        con=adb.ADB();
        Statement st;
        try {
            st = con.createStatement();//建立数据库连接
            String sql ="SELECT LENDBOOK.bno,bname,time FROM LENDBOOK,BOOK WHERE rno='"+name+"' and LENDBOOK.bno=BOOK.bno" ;
            ResultSet rs = st.executeQuery(sql);//查询
            DefaultTableModel TableModel = (DefaultTableModel) jTable3.getModel();//初始化表格
            TableModel.setRowCount(0);//清空表格内容
            while (rs.next()) {
                TableModel.addRow(new Object[]{rs.getString("bno"), rs.getString("bname"), rs.getString("time")});
            }
            rs.close();//关闭查询 
            st.close();//关闭驱动

        } catch (SQLException ex) {
        } finally {
            try {
                con.close();//关闭连接
            } catch (SQLException ex) {

            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection con = null;//调用类AcessDB和其方法connection
        AcessDB adb=new AcessDB();//建立sql数据库连接
        con=adb.ADB();
        Statement st;
        try {
            st = con.createStatement();//建立数据库连接
            String sql ="SELECT RETURNBOOK.bno,bname,time FROM RETURNBOOK,BOOK WHERE rno='"+name+"' and RETURNBOOK.bno=BOOK.bno" ;
            ResultSet rs = st.executeQuery(sql);//查询
            DefaultTableModel TableModel = (DefaultTableModel) jTable4.getModel();//初始化表格
            TableModel.setRowCount(0);//清空表格内容
            while (rs.next()) {//将搜索结果导入表格
                TableModel.addRow(new Object[]{rs.getString("bno"), rs.getString("bname"), rs.getString("time")});
            }
            rs.close();//关闭查询 
            st.close();//关闭驱动

        } catch (SQLException ex) {
        } finally {
            try {
                con.close();//关闭连接
            } catch (SQLException ex) {

            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         try {
             // TODO add your handling code here:
             
             Connection con = null;//调用类AcessDB和其方法connection
             AcessDB adb=new AcessDB();//建立sql数据库连接
             con=adb.ADB();
             Statement st;
             st = con.createStatement();//建立数据库连接
             int i = st.executeUpdate("UPDATE READER SET password= '"+jPasswordField1.getText()+"'  WHERE rno='"+name+"'");
             if (i == 1) {
                 JOptionPane.showMessageDialog(this, "密码修改成功");//弹出提示框
             }
             st.close();//关闭驱动
             con.close();//关闭连接
         } catch (SQLException ex) {
             Logger.getLogger(Reader.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton4ActionPerformed

           String a="";
    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
